TEMPLATE = app
QT = gui core xml
CONFIG += qt warn_on console debug_and_release
DESTDIR = bin
OBJECTS_DIR = build
MOC_DIR = build
UI_DIR = build
FORMS = ui/mainwindow.ui ui/printlabeldialog.ui ui/letterclient.ui
HEADERS = src/mainwindowimpl.h src/printlabeldialogimpl.h
SOURCES = src/mainwindowimpl.cpp src/main.cpp src/printlabeldialogimpl.cpp
RESOURCES += icons.qrc
